# Generated by Django 3.2.23 on 2024-02-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=256)),
                ('message', models.TextField()),
                ('have_read', models.BooleanField(default=False)),
                ('have_replied', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
