# Generated by Django 3.2.23 on 2024-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('youtube_url', models.CharField(blank=True, max_length=254, null=True)),
                ('additional_link', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
