# Generated by Django 3.2.23 on 2024-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='additional_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
