# Generated by Django 3.2.23 on 2024-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorials_youtube_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='youtube_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
