# Generated by Django 3.2.23 on 2024-01-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240120_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
    ]
