# Generated by Django 3.2.23 on 2024-03-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option_details',
        ),
        migrations.AddField(
            model_name='product',
            name='option_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_4',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_5',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
